### ISSUE TITLE
Empty checkstyle element causes an error

### ISSUE THREAD

**Issue by tkawa** [packsaddle/ruby-saddler-reporter-github#52]
I use slim-lint, it seems to produce empty `<checkstyle/>` with its own checkstyle reporter.

https://github.com/packsaddle/ruby-saddler-reporter-github/blob/master/lib/saddler/reporter/github/helper.rb#L35

log:
```
E, [2017-06-20T19:31:56.667783 #24864] ERROR -- Saddler: options
E, [2017-06-20T19:31:56.667890 #24864] ERROR -- Saddler: {"options"=>{}, "debug"=>false, "verbose"=>false, "require"=>"saddler/reporter/github", "reporter"=>"Saddler::Reporter::Github::PullRequestReviewComment"}
E, [2017-06-20T19:31:56.667978 #24864] ERROR -- Saddler: input data
E, [2017-06-20T19:31:56.668031 #24864] ERROR -- Saddler: <?xml version='1.0'?><checkstyle/>

E, [2017-06-20T19:31:56.668084 #24864] ERROR -- Saddler: reporter
E, [2017-06-20T19:31:56.668134 #24864] ERROR -- Saddler: #<Saddler::Reporter::Github::PullRequestReviewComment:0x00000002eff5b8 @output=#<IO:<STDOUT>>>
/opt/circleci/.rvm/gems/ruby-2.3.1@project2/gems/saddler-reporter-github-2.0.0/lib/saddler/reporter/github/helper.rb:35:in `build_comments_with_patches': undefined method `[]' for nil:NilClass (NoMethodError)
	from /opt/circleci/.rvm/gems/ruby-2.3.1@project2/gems/saddler-reporter-github-2.0.0/lib/saddler/reporter/github/pull_request_review_comment.rb:26:in `report'
	from /opt/circleci/.rvm/gems/ruby-2.3.1@project2/gems/saddler-1.0.0/lib/saddler/cli.rb:37:in `report'
	from /opt/circleci/.rvm/gems/ruby-2.3.1@project2/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /opt/circleci/.rvm/gems/ruby-2.3.1@project2/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/circleci/.rvm/gems/ruby-2.3.1@project2/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /opt/circleci/.rvm/gems/ruby-2.3.1@project2/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /opt/circleci/.rvm/gems/ruby-2.3.1@project2/gems/saddler-1.0.0/exe/saddler:5:in `<top (required)>'
	from /opt/circleci/.rvm/gems/ruby-2.3.1@project2/bin/saddler:23:in `load'
	from /opt/circleci/.rvm/gems/ruby-2.3.1@project2/bin/saddler:23:in `<main>'
	from /opt/circleci/.rvm/gems/ruby-2.3.1@project2/bin/ruby_executable_hooks:15:in `eval'
	from /opt/circleci/.rvm/gems/ruby-2.3.1@project2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by sanemat** [comment]
Good catch!
